### ISSUE TITLE
vs2015直接卡死编译Caffe.sln时，昨天还能编译

### ISSUE THREAD

**Issue by 12kunshou** [micvlab/doc#2]
昨天还可以用vis2015调试，今天重新生成结果就程序未响应vs2015直接卡死，电脑配置不低8g内存，gt740，i7处理器，用pycharm编译器，没摸明白怎么调试，软件没有搞明白，学长学姐能不能发个学习的网址，百度有些痛苦。一天干不了什么东西全磨蹭掉了

**Comment by walkupup** [comment]
为什么close掉了
